### ISSUE TITLE
using ViT-L/14

### ISSUE THREAD

**Issue by wmj183363206** [naver-ai/tc-clip#6]
Thank you for your work!
But when I trained based on ViT-L/14, the size of q,k,v are mismatch.

Traceback (most recent call last):
  File "main.py", line 292, in main
    main_training(logger, config)
  File "main.py", line 50, in main_training
    model = returnCLIP(config, logger, class_names)
  File "teatea/tc-clip-main/trainers/build_trainer.py", line 57, in returnCLIP
    clip_model = load_clip_to_cpu(config)
  File "teatea/tc-clip-main/trainers/build_trainer.py", line 50, in load_clip_to_cpu
    model = clip.build_model(state_dict or model.state_dict(), design_details)
  File "teatea/tc-clip-main/clip/model.py", line 265, in build_model
    model.load_state_dict(state_dict)
  File "....../site-packages/torch/nn/modules/module.py", line 1498, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for CLIP:
	Missing key(s) in state_dict: "visual.transformer.resblocks.1.attn.local_global_bias_table", ...]
        size mismatch for visual.transformer.resblocks.0.attn.q_proj.weight: copying a param with shape torch.Size([768, 1024]) from checkpoint, the shape in current model is torch.Size([1024, 1024]).
	size mismatch for visual.transformer.resblocks.0.attn.q_proj.bias: copying a param with shape torch.Size([768]) from checkpoint, the shape in current model is torch.Size([1024]).

How can I change the dim to train the TC-CLIP on Vit-L/14 ?

**Comment by wmj183363206** [comment]
I find the 'VPTextEncoder' in single_layer = PromptGenerationLayer(), and set 'use_custom_attention: false' in config. 

Is that right to finish the training TC-CLIP on ViT-L/14 ?

**Comment by wmj183363206** [comment]
Thank you for your reply.

During my experimentation, one thing that requires extra attention is 'self.return_layer_num'.

Wishing you success in your research!  : )

**Comment by silk-juan** [comment]
> Hi [@wmj183363206](https://github.com/wmj183363206) ! To use our custom attention block ([TCAttentionBlock](https://github.com/naver-ai/tc-clip/blob/d45855dc61b59c69dc0ee3b8d853535e032949b5/clip/transformer_blocks_tc.py#L19)), we recast CLIP's pretrained in_proj_weight into {q_proj.weight, k_proj.weight, v_proj.weight} as with [this code](https://github.com/naver-ai/tc-clip/blob/d45855dc61b59c69dc0ee3b8d853535e032949b5/clip/model.py#L254). Current version handles the number of parameters (channel dimensions) with hard coding, so you should change the code a bit to fit into ViT-L/14's spec. Note that ViT-B's hidden dimension is 768 but ViT-L's hidden dimension is 1024. I can update the code next week, but you can first try by fixing this part.

hello, this is a wonderful work👍 . I also came to the same problem :
   `attn_output` = scaled_dot_product_attention(q, k, v, attn_mask, dropout_p, is_causal)
RuntimeError: invalid dtype for bias - should match query's dtype``
could you tell me how can I  change the code. Thanks
